stages:
  - check

.pnpm:
  image: node:22-bookworm-slim
  cache:
    key:
      files:
        - pnpm-lock.yaml
    paths:
      - .pnpm-store
  before_script:
    - corepack enable
    - corepack prepare pnpm@10.28.1 --activate
    - pnpm config set store-dir .pnpm-store
    - pnpm install --frozen-lockfile

lint:
  extends: .pnpm
  stage: check
  script:
    - pnpm lint

typecheck:
  extends: .pnpm
  stage: check
  script:
    - pnpm typecheck

test:
  extends: .pnpm
  stage: check
  script:
    - pnpm test

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
