export const CHANGELOG_ENTRIES = [
  {
    version: '1.0.0',
    date: 'Jun 2026',
    tag: 'Launch',
    changes: [
      'The commma VS Code extension is live on the Visual Studio Marketplace — search "commma" in the Extensions panel, or install it from the web. Sign in with GitHub and your sessions, streaks, and keyboard heatmaps start filling in automatically; tracking stays key-labels-only, never the content you type',
      'The whole site now points you straight to the extension — every install button across the landing page, the top navigation, pricing, and your profile opens the Marketplace listing instead of a launch waitlist',
      'The landing "get notified" section became a "get started" section: install front and center, with its email signup repurposed to tell you when the JetBrains, Neovim, and CLI clients land',
    ],
  },
  {
    version: '0.9.0',
    date: 'Jun 2026',
    tag: 'Infra',
    changes: [
      'Continuous delivery — every change now runs an automated lint, type-check, and test gate before it can ship, and merges to the main line deploy themselves: the web app and the API release automatically, each only when its own code changes, with overlapping deploys serialized so two releases never race',
      'Fixed long usernames overflowing a feed card on narrow screens — a very long handle now truncates cleanly instead of shoving the session date out of place',
      'Backend hardening — coding activity is now accepted only with a sane timestamp (no events dated far in the future or the distant past), the sign-in rate limit is held tight in production, and the billing endpoints stay protected even if the rate limiter has a hiccup',
    ],
  },
  {
    version: '0.8.0',
    date: 'Jun 2026',
    tag: 'Release',
    changes: [
      'Docs got a home — a dedicated documentation site at docs.commma.dev covering what commma is, getting started, the architecture, system design, and self-hosting, with the API reference and changelog one click away; commma.dev/docs redirects there, and a clear "← commma.dev" button leads back to the app',
      'commma is free for everyone during early access — every Pro and Team feature is unlocked at no cost: full session history, keyboard-heatmap PNG export, the weekly recap, and team workspaces, with no card and no checkout',
      'Pricing page reworked — a new early-access section up top makes clear the $0 plan currently includes the whole product, while the Pro and Team tiers stay visible as the roadmap with "Coming later" actions',
      'Calmer landing hero — removed the cursor-following light glow and the sweeping scan line over the keyboard',
      'Copy pass for the free launch — the landing signup is now a launch-notify list (not an invite gate), the home and status pages drop the "invite-only" language, and the final call-to-action starts you free instead of pointing at pricing',
      'Fixed the About page stack cards on mobile — tapping a card to expand it no longer clips the long entries (Terraform, Neon, Upstash), and cards no longer jitter when scrolling past them',
      'Infrastructure as code — the entire AWS footprint (compute, web CDN, DNS, TLS certificate, and IAM) is now managed with Terraform, adopted from the live stack with zero downtime, so every infrastructure change ships as a reviewed, reproducible plan instead of a console click',
      'Security hardening — the API server’s disk is now encrypted at rest (with encryption enforced on every future volume) and administrative SSH access is locked to a single operator address',
      'Smoother scrolling — fixed page-wide scroll lag caused by the textured background repainting on every frame, lightened the landing-page background glow, made the scroll-progress bar cheaper to update, and stopped the landing live-keyboard animation from running once it scrolls off-screen',
      'Fixed every "Install the extension" button (landing, nav, pricing) pointing nowhere useful — they now link to the waitlist signup, and your own empty profile explains the extension is not public yet instead of just saying "No sessions yet"',
    ],
  },
  {
    version: '0.7.0',
    date: 'Jun 2026',
    tag: 'Release',
    changes: [
      'Team workspaces leveled up — the dashboard now uses a balanced two-column layout with a first-run prompt, every control meets the mobile tap-target and readable-text minimums, and a Team plan can create up to two teams (joining other teams stays unlimited and free)',
      'Paid plans are live — subscribe to Pro or Team with a card through secure Stripe checkout, switch between monthly and annual billing, and manage or cancel anytime from the billing portal',
      'Brand film on the About page — a 15-second teaser that floods the keyboard with heat, scores the session like a race, and lands on the wordmark; autoplays muted in view, pauses off-screen, and respects reduced-motion',
      'commma is now on LinkedIn — linked from the site footer, the Contact page, and Organization structured data',
      'Landing hero reimagined around a live keyboard heatmap — a self-typing board floods keys with heat in real time, with a live keys-per-minute, top-key, and session readout',
      'Every landing section rebuilt with oversized index numerals, scroll-reveal motion, and a broadcast-style live activity ticker',
      'New headline — "Every keystroke leaves a mark"',
      'Back-to-top button now appears on every page, not just the landing page',
      'Join the waitlist — a new section on the landing page captures your email and sends a confirmation, so you get pinged the moment the next access wave opens',
      'Fixed streak-reminder notifications — enabling them now recovers from a stale subscription, explains the Add-to-Home-Screen step on iPhone/iPad, and reports any browser refusal instead of silently doing nothing',
      'Streak reminders now send at a fixed daily time and survive server restarts, so they fire reliably',
    ],
  },
  {
    version: '0.6.0',
    date: 'Jun 2026',
    tag: 'Design',
    changes: [
      'Depth pass across every page — raised cards, recessed inputs, a floating navbar, lifted headlines, and glowing CTAs, all lit from above (palette, type, and colors unchanged)',
      'Landing hero is now a cursor-driven 3D scene: parallax depth layers, an accent light that follows your cursor, and a tilting glass stat panel with a moving glare',
      'Always-on 3D backdrop on the landing page — a perspective speed-grid tunnel and drifting glow-orbs, rendered in pure CSS so the motion runs on mobile too',
      'Motion respects prefers-reduced-motion, and cursor-only effects switch off on touch devices',
    ],
  },
  {
    version: '0.5.0',
    date: 'Jun 2026',
    tag: 'Production',
    changes: [
      'commma.dev is live — deployed on AWS (EC2 t4g + PM2 for the API, S3 + CloudFront for the web) with Neon Postgres and Upstash Redis; TLS everywhere',
      'Backend hardening: graceful SIGTERM shutdown, scheduler leader lock (safe to run on multiple instances), rate limiter fails closed on Redis outage for auth and ingest routes',
      'Fixed empty-leaderboard cold-rebuild race condition — negative cache reduces read p95 from ~2 s to ~161 ms under concurrency',
      'Session-detail back link is origin-aware: shows "Back to @handle" when navigating from a profile page',
      'Weekly recap email delivered from recap@commma.dev (verified sender domain on Resend)',
      'One-command deploy scripts: pnpm deploy:web and pnpm deploy:api',
    ],
  },
  {
    version: '0.4.0',
    date: 'Jun 2026',
    tag: 'Phase 4 cont.',
    changes: [
      'About page — origin story, animated GitHub × Strava insight, manifesto, and 23-entry stack catalogue grouped by layer',
      'Weekly recap page for Pro and Team users — live in-app version of the Monday summary email',
      'Weekly recap email — Monday morning session summary with AI-assisted prose for Pro and Team users',
      'Current plan highlighted on Pricing; paid users get a "Manage billing" portal link',
      'Team workspaces: invite members, private leaderboard, aggregate keyboard heatmap',
      'Push notifications for streak reminders (browser Web Push, opt-in)',
      'PWA: installable on Android and iOS, offline fallback via service worker',
      'Server-side keyboard heatmap PNG for sharing and OG cards',
      'Smart navbar: hides on scroll-down, reveals on any upward scroll',
      'Extension first-run sign-in nudge — one-time prompt after install',
    ],
  },
  {
    version: '0.3.0',
    date: 'Jun 2026',
    tag: 'Phase 4',
    changes: [
      'Style badges on profiles: Vim athlete, Mouse-free, Backspace heavy, Arrow navigator',
      'Dvorak and Colemak keyboard layout toggle on the heatmap',
      'Stripe billing: Pro ($5/mo) and Team ($20/mo, up to 5 seats)',
      'PNG export gated to Pro plan; free users see an upgrade prompt',
      'Pricing page with Free / Pro / Team tiers',
    ],
  },
  {
    version: '0.2.0',
    date: 'May 2026',
    tag: 'Phase 2 – 3',
    changes: [
      'Profile pages at /@handle with live session feed and stat grid',
      'Leaderboard — week / month / all-time periods',
      'Community feed with follow / unfollow',
      'Keyboard heatmap PNG export (1:1, 9:16, 16:9 presets)',
      'GitHub OAuth sign-in from the web app',
      'Privacy modes: full / summary / off enforced server-side',
      'Rate limiting on all endpoints (Redis fixed-window)',
    ],
  },
  {
    version: '0.1.0',
    date: 'May 2026',
    tag: 'Phase 1',
    changes: [
      'VSCode extension: keystroke tracking, 60-second heartbeat flush to API',
      'Session aggregation with 15-minute idle gap detection',
      'Keyboard heatmap built from key-label frequency data',
      'Streak tracking and leaderboard sorted sets',
      'Session detail page with language breakdown and file list',
    ],
  },
] as const

export const LATEST_VERSION = CHANGELOG_ENTRIES[0].version
